import type { Manifest } from "./harness.js";

// Every request the parity harness sends to both servers. compare: body = byte-equal body, json = equal
// as JSON, markdown = byte-equal with the first difference reported,
// headers = status and the recorded headers only. Every entry compares status and headers.
export const MANIFEST: Manifest = {
  headers: {"x-forwarded-for":"203.0.113.7"},
  requests: [
    {"name":"index","path":"/","compare":"headers"},
    {"name":"index-before","path":"/?before=2026-09-01","compare":"headers"},
    {"name":"index-year","path":"/?year=2026","compare":"headers"},
    {"name":"index-notice","path":"/?subscribed=1","compare":"headers"},
    {"name":"index-markdown","path":"/","headers":{"accept":"text/markdown"},"compare":"body"},
    {"name":"index-406","path":"/","headers":{"accept":"application/json"},"compare":"body"},
    {"name":"index-md","path":"/index.md","compare":"body"},
    {"name":"archive-before","path":"/archive?before=2026-09-01","compare":"headers"},
    {"name":"archive-year","path":"/archive?year=2025","compare":"headers"},
    {"name":"issue-latest","path":"/issues/2026-09-23","compare":"headers"},
    {"name":"issue-march","path":"/issues/2026-03-01","compare":"headers"},
    {"name":"issue-no-run","path":"/issues/2025-12-26","compare":"headers"},
    {"name":"issue-md-latest","path":"/issues/2026-09-23.md","compare":"markdown"},
    {"name":"issue-md-march","path":"/issues/2026-03-01.md","compare":"markdown"},
    {"name":"issue-md-first","path":"/issues/2025-12-05.md","compare":"markdown"},
    {"name":"issue-md-july","path":"/issues/2026-07-01.md","compare":"markdown"},
    {"name":"issue-negotiated-md","path":"/issues/2026-09-22","headers":{"accept":"text/markdown, text/html"},"compare":"markdown"},
    {"name":"issue-406","path":"/issues/2026-09-22","headers":{"accept":"image/png"},"compare":"body"},
    {"name":"issue-absent","path":"/issues/2019-01-01","compare":"headers"},
    {"name":"issue-not-a-date","path":"/issues/not-a-date","compare":"headers"},
    {"name":"today","path":"/today","compare":"headers"},
    {"name":"today-translate","path":"/today/translate","compare":"headers"},
    {"name":"today-translate-de","path":"/today/translate?lang=de","compare":"headers"},
    {"name":"today-translate-en","path":"/today/translate?lang=en","compare":"headers"},
    {"name":"legacy-date","path":"/2026-09-01","compare":"headers"},
    {"name":"legacy-date-md","path":"/2026-09-01.md","compare":"headers"},
    {"name":"legacy-translate","path":"/2026-09-01/translate?lang=fr","compare":"headers"},
    {"name":"legacy-not-a-date","path":"/about","compare":"headers"},
    {"name":"translate-issue","path":"/issues/2026-09-01/translate","headers":{"accept-language":"fr-CA,fr;q=0.9,en;q=0.8"},"compare":"headers"},
    {"name":"translate-issue-default","path":"/issues/2026-09-01/translate","compare":"headers"},
    {"name":"translate-issue-absent","path":"/issues/2019-01-01/translate","compare":"headers"},
    {"name":"translate-issue-bad","path":"/issues/not-a-date/translate","compare":"headers"},
    {"name":"translate-page","path":"/translate?to=/stats","compare":"headers"},
    {"name":"translate-page-offsite","path":"/translate?to=//evil.example","compare":"headers"},
    {"name":"translate-page-bare","path":"/translate","compare":"headers"},
    {"name":"feed","path":"/feed.xml","compare":"body"},
    {"name":"search-empty","path":"/search","compare":"headers"},
    {"name":"search-word","path":"/search?q=ceasefire","compare":"headers"},
    {"name":"search-phrase","path":"/search?q=Iran%20nuclear","compare":"headers"},
    {"name":"search-none","path":"/search?q=zzqqxxnotaword","compare":"headers"},
    {"name":"search-operators","path":"/search?q=%22ceasefire%22%20OR%20gaza*%20NOT%20(x)%20headline%3Ay","compare":"headers"},
    {"name":"archive-bare","path":"/archive","compare":"headers"},
    {"name":"archive-bad-limit","path":"/archive?limit=abc","compare":"headers"},
    {"name":"threads","path":"/threads","compare":"headers"},
    {"name":"threads-more","path":"/threads/more?before=2026-09-01%2000%3A00%3A00&before_id=999999","compare":"headers"},
    {"name":"threads-half-cursor","path":"/threads?before=2026-09-01","compare":"headers"},
    {"name":"threads-empty-cursor","path":"/threads/more?before=&before_id=1","compare":"headers"},
    {"name":"thread-active","path":"/thread/634","compare":"headers"},
    {"name":"thread-dormant","path":"/thread/837","compare":"headers"},
    {"name":"thread-absent","path":"/thread/99999999","compare":"headers"},
    {"name":"thread-not-a-number","path":"/thread/abc","compare":"headers"},
    {"name":"stats","path":"/stats","compare":"headers"},
    {"name":"stats-7","path":"/stats?days=7","compare":"headers"},
    {"name":"stats-90","path":"/stats?days=90","compare":"headers"},
    {"name":"stats-json","path":"/stats.json","compare":"json"},
    {"name":"stats-json-7","path":"/stats.json?days=7","compare":"json"},
    {"name":"stats-json-90","path":"/stats.json?days=90","compare":"json"},
    {"name":"stats-json-all","path":"/stats.json?days=3650","compare":"json"},
    {"name":"stats-json-bad-days","path":"/stats.json?days=abc","compare":"headers"},
    {"name":"stats-odd-days","path":"/stats?days=5","compare":"headers"},
    {"name":"stats-trailing-slash","path":"/stats/","compare":"headers"},
    {"name":"sources","path":"/sources","compare":"headers"},
    {"name":"sources-trailing-slash","path":"/sources/","compare":"headers"},
    {"name":"feedback","path":"/feedback","compare":"headers"},
    {"name":"privacy","path":"/privacy","compare":"headers"},
    {"name":"llms","path":"/llms.txt","compare":"body"},
    {"name":"llms-full","path":"/llms-full.txt","compare":"headers"},
    {"name":"robots","path":"/robots.txt","compare":"body"},
    {"name":"health","path":"/health","compare":"json"},
    {"name":"favicon","path":"/favicon.ico","compare":"body"},
    {"name":"apple-touch-icon","path":"/apple-touch-icon.png","compare":"body"},
    {"name":"apple-touch-icon-precomposed","path":"/apple-touch-icon-precomposed.png","compare":"body"},
    {"name":"og-image","path":"/og-image.png","compare":"body"},
    {"name":"font","path":"{font}","compare":"body"},
    {"name":"not-found","path":"/no/such/page","compare":"headers"},
    {"name":"issue-trailing-slash","path":"/issues/2026-09-01/","compare":"headers"},
    {"name":"wrong-method-subscribe","path":"/subscribe","compare":"headers"},
    {"name":"wrong-method-feed","method":"POST","path":"/feed.xml","compare":"headers"},
    {"name":"head-index","method":"HEAD","path":"/","compare":"headers"},
    {"name":"head-feed","method":"HEAD","path":"/feed.xml","compare":"headers"},
    {"name":"subscribe-invalid","method":"POST","path":"/subscribe","headers":{"content-type":"application/x-www-form-urlencoded"},"body":"email=not-an-address","compare":"headers"},
    {"name":"subscribe-off","method":"POST","path":"/subscribe","headers":{"content-type":"application/x-www-form-urlencoded"},"body":"email=reader%40example.com","compare":"headers"},
    {"name":"confirm-off","path":"/confirm?token=abc.def","compare":"headers"},

    {"name":"rate-limit-subscribe","method":"POST","path":"/subscribe","headers":{"content-type":"application/x-www-form-urlencoded","x-forwarded-for":"198.51.100.3"},"body":"email=reader%40example.com","repeat":6,"compare":"headers"},
  ],
};
