import type { Manifest } from "./harness.js";

// Every request the parity harness sends to both servers. compare: body = byte-equal body, json = equal
// as JSON, markdown = byte-equal with the first difference reported, search = the same result set,
// headers = status and the recorded headers only. Every entry compares status and headers.
export const MANIFEST: Manifest = {
  headers: {"x-forwarded-for":"203.0.113.7"},
  requests: [
    {"name":"index","path":"/","compare":"headers"},
    {"name":"index-before","path":"/?before=2026-09-01","compare":"headers"},
    {"name":"index-year","path":"/?year=2026","compare":"headers"},
    {"name":"index-notice","path":"/?subscribed=1","compare":"headers"},
    {"name":"index-markdown","path":"/","headers":{"accept":"text/markdown"},"compare":"body"},
    {"name":"index-406","path":"/","headers":{"accept":"application/json"},"compare":"body"},
    {"name":"index-md","path":"/index.md","compare":"body"},
    {"name":"archive-before","path":"/archive?before=2026-09-01","compare":"headers"},
    {"name":"archive-year","path":"/archive?year=2025","compare":"headers"},
    {"name":"issue-latest","path":"/issues/2026-09-23","compare":"headers"},
    {"name":"issue-march","path":"/issues/2026-03-01","compare":"headers"},
    {"name":"issue-no-run","path":"/issues/2025-12-26","compare":"headers"},
    {"name":"issue-md-latest","path":"/issues/2026-09-23.md","compare":"markdown"},
    {"name":"issue-md-march","path":"/issues/2026-03-01.md","compare":"markdown"},
    {"name":"issue-md-first","path":"/issues/2025-12-05.md","compare":"markdown"},
    {"name":"issue-md-july","path":"/issues/2026-07-01.md","compare":"markdown"},
    {"name":"issue-negotiated-md","path":"/issues/2026-09-22","headers":{"accept":"text/markdown, text/html"},"compare":"markdown"},
    {"name":"issue-406","path":"/issues/2026-09-22","headers":{"accept":"image/png"},"compare":"body"},
    {"name":"issue-absent","path":"/issues/2019-01-01","compare":"headers"},
    {"name":"issue-not-a-date","path":"/issues/not-a-date","compare":"headers"},
    {"name":"today","path":"/today","compare":"headers"},
    {"name":"today-translate","path":"/today/translate","compare":"headers"},
    {"name":"today-translate-de","path":"/today/translate?lang=de","compare":"headers"},
    {"name":"today-translate-en","path":"/today/translate?lang=en","compare":"headers"},
    {"name":"legacy-date","path":"/2026-09-01","compare":"headers"},
    {"name":"legacy-date-md","path":"/2026-09-01.md","compare":"headers"},
    {"name":"legacy-translate","path":"/2026-09-01/translate?lang=fr","compare":"headers"},
    {"name":"legacy-not-a-date","path":"/about","compare":"headers"},
    {"name":"translate-issue","path":"/issues/2026-09-01/translate","headers":{"accept-language":"fr-CA,fr;q=0.9,en;q=0.8"},"compare":"headers"},
    {"name":"translate-issue-default","path":"/issues/2026-09-01/translate","compare":"headers"},
    {"name":"translate-issue-absent","path":"/issues/2019-01-01/translate","compare":"headers"},
    {"name":"translate-issue-bad","path":"/issues/not-a-date/translate","compare":"headers"},
    {"name":"translate-page","path":"/translate?to=/stats","compare":"headers"},
    {"name":"translate-page-offsite","path":"/translate?to=//evil.example","compare":"headers"},
    {"name":"translate-page-bare","path":"/translate","compare":"headers"},
    {"name":"feed","path":"/feed.xml","compare":"body"},
    {"name":"search-empty","path":"/search","compare":"headers"},
    {"name":"search-word","path":"/search?q=ceasefire","compare":"headers"},
    {"name":"search-phrase","path":"/search?q=Iran%20nuclear","compare":"headers"},
    {"name":"search-none","path":"/search?q=zzqqxxnotaword","compare":"headers"},
    {"name":"search-operators","path":"/search?q=%22ceasefire%22%20OR%20gaza*%20NOT%20(x)%20headline%3Ay","compare":"headers"},
    {"name":"archive-bare","path":"/archive","compare":"headers"},
    {"name":"archive-bad-limit","path":"/archive?limit=abc","compare":"headers"},
    {"name":"threads","path":"/threads","compare":"headers"},
    {"name":"threads-more","path":"/threads/more?before=2026-09-01%2000%3A00%3A00&before_id=999999","compare":"headers"},
    {"name":"threads-half-cursor","path":"/threads?before=2026-09-01","compare":"headers"},
    {"name":"threads-empty-cursor","path":"/threads/more?before=&before_id=1","compare":"headers"},
    {"name":"thread-active","path":"/thread/634","compare":"headers"},
    {"name":"thread-dormant","path":"/thread/837","compare":"headers"},
    {"name":"thread-absent","path":"/thread/99999999","compare":"headers"},
    {"name":"thread-not-a-number","path":"/thread/abc","compare":"headers"},
    {"name":"stats","path":"/stats","compare":"headers"},
    {"name":"stats-7","path":"/stats?days=7","compare":"headers"},
    {"name":"stats-90","path":"/stats?days=90","compare":"headers"},
    {"name":"stats-json","path":"/stats.json","compare":"json"},
    {"name":"stats-json-7","path":"/stats.json?days=7","compare":"json"},
    {"name":"stats-json-90","path":"/stats.json?days=90","compare":"json"},
    {"name":"stats-json-all","path":"/stats.json?days=3650","compare":"json"},
    {"name":"stats-json-bad-days","path":"/stats.json?days=abc","compare":"headers"},
    {"name":"stats-odd-days","path":"/stats?days=5","compare":"headers"},
    {"name":"stats-trailing-slash","path":"/stats/","compare":"headers"},
    {"name":"sources","path":"/sources","compare":"headers"},
    {"name":"sources-trailing-slash","path":"/sources/","compare":"headers"},
    {"name":"ask-page","path":"/ask","compare":"headers"},
    {"name":"connect","path":"/connect","compare":"headers"},
    {"name":"feedback","path":"/feedback","compare":"headers"},
    {"name":"privacy","path":"/privacy","compare":"headers"},
    {"name":"llms","path":"/llms.txt","compare":"body"},
    {"name":"llms-full","path":"/llms-full.txt","compare":"headers"},
    {"name":"robots","path":"/robots.txt","compare":"body"},
    {"name":"health","path":"/health","compare":"json"},
    {"name":"favicon","path":"/favicon.ico","compare":"body"},
    {"name":"apple-touch-icon","path":"/apple-touch-icon.png","compare":"body"},
    {"name":"apple-touch-icon-precomposed","path":"/apple-touch-icon-precomposed.png","compare":"body"},
    {"name":"og-image","path":"/og-image.png","compare":"body"},
    {"name":"font","path":"{font}","compare":"body"},
    {"name":"not-found","path":"/no/such/page","compare":"headers"},
    {"name":"issue-trailing-slash","path":"/issues/2026-09-01/","compare":"headers"},
    {"name":"wrong-method-subscribe","path":"/subscribe","compare":"headers"},
    {"name":"wrong-method-ask-json","path":"/ask.json","compare":"headers"},
    {"name":"wrong-method-mcp","method":"DELETE","path":"/mcp","compare":"headers"},
    {"name":"wrong-method-feed","method":"POST","path":"/feed.xml","compare":"headers"},
    {"name":"head-index","method":"HEAD","path":"/","compare":"headers"},
    {"name":"head-feed","method":"HEAD","path":"/feed.xml","compare":"headers"},
    {"name":"subscribe-invalid","method":"POST","path":"/subscribe","headers":{"content-type":"application/x-www-form-urlencoded"},"body":"email=not-an-address","compare":"headers"},
    {"name":"subscribe-off","method":"POST","path":"/subscribe","headers":{"content-type":"application/x-www-form-urlencoded"},"body":"email=reader%40example.com","compare":"headers"},
    {"name":"confirm-off","path":"/confirm?token=abc.def","compare":"headers"},
    {"name":"ask-json-off","method":"POST","path":"/ask.json","headers":{"content-type":"application/json"},"body":"{\"question\":\"What happened?\"}","compare":"json"},
    {"name":"ask-stream-off","method":"POST","path":"/ask","headers":{"content-type":"application/json"},"body":"{\"question\":\"What happened?\"}","compare":"body"},
    {"name":"mcp-listing","path":"/mcp","compare":"body"},
    {"name":"mcp-card","path":"/.well-known/mcp.json","compare":"json"},
    {"name":"mcp-card-legacy","path":"/.well-known/mcp/server-card.json","compare":"json"},
    {"name":"mcp-tools","path":"/mcp/tools.json","compare":"json"},
    {"name":"rpc-initialize","rpc":{"method":"initialize","params":{"protocolVersion":"2025-11-25","capabilities":{},"clientInfo":{"name":"parity","version":"1"}}},"compare":"json"},
    {"name":"rpc-tools-list","rpc":{"method":"tools/list"},"compare":"json"},
    {"name":"rpc-latest-issue","rpc":{"method":"tools/call","params":{"name":"get_latest_issue","arguments":{}}},"compare":"json"},
    {"name":"rpc-issue","rpc":{"method":"tools/call","params":{"name":"get_issue","arguments":{"date":"2026-09-01"}}},"compare":"json"},
    {"name":"rpc-issue-absent","rpc":{"method":"tools/call","params":{"name":"get_issue","arguments":{"date":"2019-01-01"}}},"compare":"json"},
    {"name":"rpc-issue-bad-date","rpc":{"method":"tools/call","params":{"name":"get_issue","arguments":{"date":"yesterday"}}},"compare":"json"},
    {"name":"rpc-list-issues","rpc":{"method":"tools/call","params":{"name":"list_issues","arguments":{}}},"compare":"json"},
    {"name":"rpc-list-issues-5","rpc":{"method":"tools/call","params":{"name":"list_issues","arguments":{"limit":5}}},"compare":"json"},
    {"name":"rpc-search","rpc":{"method":"tools/call","params":{"name":"search_headlines","arguments":{"query":"ceasefire"}}},"compare":"search"},
    {"name":"rpc-search-phrase","rpc":{"method":"tools/call","params":{"name":"search_headlines","arguments":{"query":"Iran nuclear"}}},"compare":"search"},
    {"name":"rpc-search-none","rpc":{"method":"tools/call","params":{"name":"search_headlines","arguments":{"query":"zzqqxxnotaword"}}},"compare":"json"},
    {"name":"rpc-search-blank","rpc":{"method":"tools/call","params":{"name":"search_headlines","arguments":{"query":"   "}}},"compare":"json"},
    {"name":"rpc-search-operators","rpc":{"method":"tools/call","params":{"name":"search_headlines","arguments":{"query":"\"Iran\" AND nuclear* OR (x) headline:y"}}},"compare":"json"},
    {"name":"rpc-list-issues-0","rpc":{"method":"tools/call","params":{"name":"list_issues","arguments":{"limit":0}}},"compare":"json"},
    {"name":"rpc-list-issues-1000","rpc":{"method":"tools/call","params":{"name":"list_issues","arguments":{"limit":1000}}},"compare":"json"},
    {"name":"rpc-stats-huge","rpc":{"method":"tools/call","params":{"name":"get_stats","arguments":{"days":999999}}},"compare":"json"},
    {"name":"rpc-list-threads","rpc":{"method":"tools/call","params":{"name":"list_threads","arguments":{}}},"compare":"json","known":"threads.updated_at is not derivable; the new value is the latest published update's time (fork doc §5 item 2)"},
    {"name":"rpc-list-threads-3","rpc":{"method":"tools/call","params":{"name":"list_threads","arguments":{"limit":3}}},"compare":"json","known":"threads.updated_at is not derivable; the new value is the latest published update's time (fork doc §5 item 2)"},
    {"name":"rpc-thread","rpc":{"method":"tools/call","params":{"name":"get_thread","arguments":{"id":634}}},"compare":"json"},
    {"name":"rpc-thread-dormant","rpc":{"method":"tools/call","params":{"name":"get_thread","arguments":{"id":837}}},"compare":"json"},
    {"name":"rpc-thread-absent","rpc":{"method":"tools/call","params":{"name":"get_thread","arguments":{"id":99999999}}},"compare":"json"},
    {"name":"rpc-thread-zero","rpc":{"method":"tools/call","params":{"name":"get_thread","arguments":{"id":0}}},"compare":"json"},
    {"name":"rpc-sources","rpc":{"method":"tools/call","params":{"name":"get_sources","arguments":{}}},"compare":"json"},
    {"name":"rpc-stats","rpc":{"method":"tools/call","params":{"name":"get_stats","arguments":{}}},"compare":"json"},
    {"name":"rpc-stats-7","rpc":{"method":"tools/call","params":{"name":"get_stats","arguments":{"days":7}}},"compare":"json"},
    {"name":"rpc-unknown-tool","rpc":{"method":"tools/call","params":{"name":"no_such_tool","arguments":{}}},"compare":"json"},
    {"name":"rpc-prompts-list","rpc":{"method":"prompts/list"},"compare":"json"},
    {"name":"rpc-resources-list","rpc":{"method":"resources/list"},"compare":"json"},
    {"name":"rpc-resource-templates-list","rpc":{"method":"resources/templates/list"},"compare":"json"},
    {"name":"rpc-unknown-method","rpc":{"method":"no/such/method"},"compare":"json"},
    {"name":"rpc-no-accept","rpc":{"method":"tools/list"},"headers":{"accept":"application/json"},"compare":"headers","known":"the MCP SDK answers a refused transport request with a JSON-RPC error body where rmcp sent text (fork doc §5)"},
    {"name":"rpc-malformed","rpc":{"method":"tools/list"},"body":"{\"jsonrpc\":\"2.0\",\"id\":1,","compare":"headers","known":"an unparseable body is a JSON-RPC parse error (400) in the MCP SDK, where rmcp answered 415 (fork doc §5)"},
    {"name":"rpc-wrong-content-type","rpc":{"method":"tools/list"},"headers":{"content-type":"text/plain"},"compare":"headers","known":"the MCP SDK answers a refused transport request with a JSON-RPC error body where rmcp sent text (fork doc §5)"},
    {"name":"bridge-latest-issue","path":"/mcp/tools/get_latest_issue.json","compare":"json"},
    {"name":"bridge-issue","path":"/mcp/tools/get_issue.json?date=2026-09-01","compare":"json"},
    {"name":"bridge-issue-absent","path":"/mcp/tools/get_issue.json?date=2019-01-01","compare":"json"},
    {"name":"bridge-issue-missing-arg","path":"/mcp/tools/get_issue.json","compare":"json"},
    {"name":"bridge-issue-too-long","path":"/mcp/tools/get_issue.json?date={x201}","compare":"json"},
    {"name":"bridge-list-issues","path":"/mcp/tools/list_issues.json?limit=5","compare":"json"},
    {"name":"bridge-search","path":"/mcp/tools/search_headlines.json?query=ceasefire","compare":"search"},
    {"name":"bridge-list-threads","path":"/mcp/tools/list_threads.json?limit=3","compare":"json","known":"threads.updated_at is not derivable; the new value is the latest published update's time (fork doc §5 item 2)"},
    {"name":"bridge-thread","path":"/mcp/tools/get_thread.json?id=634","compare":"json"},
    {"name":"bridge-thread-not-a-number","path":"/mcp/tools/get_thread.json?id=abc","compare":"json"},
    {"name":"bridge-sources","path":"/mcp/tools/get_sources.json","compare":"json"},
    {"name":"bridge-stats","path":"/mcp/tools/get_stats.json?days=30","compare":"json"},
    {"name":"bridge-unknown-tool","path":"/mcp/tools/no_such_tool.json","compare":"json"},
    {"name":"bridge-no-suffix","path":"/mcp/tools/get_issue","compare":"json"},
    {"name":"bridge-limit-not-a-number","path":"/mcp/tools/list_issues.json?limit=abc","compare":"json"},

    {"name":"rate-limit-mcp","rpc":{"method":"tools/list"},"headers":{"x-forwarded-for":"198.51.100.1"},"repeat":121,"compare":"json"},
    {"name":"rate-limit-bridge","path":"/mcp/tools/get_sources.json","headers":{"x-forwarded-for":"198.51.100.2"},"repeat":121,"compare":"json"},
    {"name":"rate-limit-subscribe","method":"POST","path":"/subscribe","headers":{"content-type":"application/x-www-form-urlencoded","x-forwarded-for":"198.51.100.3"},"body":"email=reader%40example.com","repeat":6,"compare":"headers"},
  ],
};
