-- migrate:up

-- The product schema after the Python pipeline (docs/2026-09-23-data-model-design.md §4, and the
-- Postgres decision at its top; names follow its "Naming" section). Written fresh: bin/import-legacy
-- copies today's SQLite data into it. Times are timestamptz in UTC. Ids are identities BY DEFAULT so
-- the import can keep the legacy ids.

CREATE TABLE runs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at    timestamptz NOT NULL DEFAULT now(),
  articles_kept integer,
  git_sha       text,
  status        text NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
  -- 'unrecorded': imported Python runs marked completed with no evidence of a send.
  outcome       text CHECK (outcome IN ('sent', 'disabled', 'rejected', 'held-out', 'skipped', 'unrecorded')),
  error         text,
  CHECK ((status = 'completed') = (outcome IS NOT NULL))
);
CREATE INDEX runs_started_at ON runs (started_at);

-- The lifecycle (§4.1): running -> completed(outcome) | failed; failed -> running (a resume);
-- completed -> running only while readers have nothing of it: not sent, and not in published_runs.
-- A published run is terminal: a forced re-run of its day is a new run. A write that leaves status
-- and outcome as they were is always allowed.
CREATE FUNCTION runs_transition() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW.status = OLD.status AND NEW.outcome IS NOT DISTINCT FROM OLD.outcome)
     OR (OLD.status = 'running' AND NEW.status IN ('completed', 'failed'))
     OR (OLD.status = 'failed' AND NEW.status = 'running')
     OR (OLD.status = 'completed' AND OLD.outcome <> 'sent' AND NEW.status = 'running'
         AND NOT EXISTS (SELECT 1 FROM published_runs p WHERE p.run_id = OLD.id)) THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'illegal run transition: % (%) -> % (%)', OLD.status, OLD.outcome, NEW.status, NEW.outcome
    USING ERRCODE = 'check_violation';
END
$$;
CREATE TRIGGER runs_transition BEFORE UPDATE OF status, outcome ON runs
  FOR EACH ROW EXECUTE FUNCTION runs_transition();

-- One execution of a run: a Python process, or a Temporal workflow run (workflow_id and
-- workflow_run_id are Temporal's own ids).
CREATE TABLE run_attempts (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id          bigint NOT NULL REFERENCES runs (id),
  pipeline        text NOT NULL CHECK (pipeline IN ('python', 'temporal')),
  workflow_id     text,
  workflow_run_id text UNIQUE,
  git_sha         text,
  is_forced       boolean NOT NULL DEFAULT false,
  started_at      timestamptz NOT NULL DEFAULT now(),
  ended_at        timestamptz,
  status          text NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
  error           text
);
CREATE INDEX run_attempts_run ON run_attempts (run_id);

-- A row is never overwritten: quarantine and force mark the old row and keep it, so the prior sample
-- survives, attributed to the attempt that produced it.
CREATE TABLE artifacts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id     bigint NOT NULL REFERENCES runs (id),
  attempt_id bigint REFERENCES run_attempts (id),
  name       text NOT NULL,
  content    text NOT NULL,
  sha256     text NOT NULL,
  status     text NOT NULL DEFAULT 'current' CHECK (status IN ('current', 'quarantined', 'replaced')),
  stage      text,
  kind       text,
  branch     text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX artifacts_current ON artifacts (run_id, name) WHERE status = 'current';
CREATE INDEX artifacts_run ON artifacts (run_id);

-- One row per system prompt and tool configuration, by content hash: local, A/B and replay runs have
-- no trustworthy image SHA, so git_sha cannot version a prompt.
CREATE TABLE prompts (
  sha256       text PRIMARY KEY,
  name         text NOT NULL,
  body         text NOT NULL,
  first_run_id bigint REFERENCES runs (id)
);

-- One row per model call. Its inputs and output are artifacts (the corpus); full traces are not kept.
-- Token columns carry OpenTelemetry's gen_ai.usage.* names with the dots as underscores, but
-- input_tokens is the provider's count EXCLUDING the cache: OpenTelemetry's input_tokens is the sum
-- of all three input columns.
CREATE TABLE model_calls (
  id                          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id                      bigint NOT NULL REFERENCES runs (id),
  attempt_id                  bigint REFERENCES run_attempts (id),
  stage                       text NOT NULL,
  branch                      text,
  request_model               text NOT NULL,
  input_tokens                integer NOT NULL DEFAULT 0,
  output_tokens               integer NOT NULL DEFAULT 0,
  cache_creation_input_tokens integer NOT NULL DEFAULT 0,
  cache_read_input_tokens     integer NOT NULL DEFAULT 0,
  api_cost_usd                double precision NOT NULL DEFAULT 0,
  duration_ms                 integer,
  thinking                    text,
  effort                      text,
  prompt_sha256               text REFERENCES prompts (sha256),
  input_manifest              jsonb,
  output_artifact             text,
  outcome                     text CHECK (outcome IN ('ok', 'invalid', 'error', 'timeout')),
  recorded_at                 timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX model_calls_run ON model_calls (run_id);

-- The web publication, append-only: a forced re-run adds a revision, never overwrites one. Inserted
-- after the pre-send hold, so an issue row means readers can see it. run_id is NULL only on five
-- issues imported from before runs were linked to issues.
CREATE TABLE issues (
  issue_date   date NOT NULL,
  revision     integer NOT NULL CHECK (revision >= 1),
  run_id       bigint REFERENCES runs (id),
  html         text NOT NULL,
  preheader    text NOT NULL DEFAULT '',
  published_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (issue_date, revision)
);
CREATE INDEX issues_run ON issues (run_id);

-- The day's email, one per date: inserting the row is taking the claim. claim_token and claimed_at
-- are NULL only on sends imported from before claims were recorded, and resend_id (Resend's
-- broadcast id) on those from before broadcasts.
CREATE TABLE sends (
  issue_date  date PRIMARY KEY,
  run_id      bigint NOT NULL REFERENCES runs (id),
  claim_token uuid,
  claimed_at  timestamptz,
  resend_id   text UNIQUE,
  revision    integer NOT NULL,
  status      text NOT NULL CHECK (status IN ('claimed', 'draft', 'queued', 'sending', 'sent', 'failed')),
  recipients  integer,
  FOREIGN KEY (issue_date, revision) REFERENCES issues (issue_date, revision)
);
CREATE INDEX sends_run ON sends (run_id);

-- The one definition of "readers got this run": on the web, or handed to Resend (which cannot recall it).
CREATE VIEW published_runs AS
  SELECT run_id FROM issues WHERE run_id IS NOT NULL
  UNION
  SELECT run_id FROM sends WHERE status IN ('queued', 'sending', 'sent');

-- The runs whose digest was emailed, by the run's own record: what the next day's context, the fetch
-- age filter, the one-run-a-day guard and thread ageing count. Not published_runs: an issue is on the
-- web before its send, and a send that then fails leaves a run readers were not emailed. 'unrecorded'
-- counts because the Python pipeline counted it (it marked every completed run as emailed).
CREATE VIEW sent_runs AS
  SELECT id AS run_id FROM runs WHERE outcome IN ('sent', 'unrecorded');

-- One row per source article cited under a story in an issue; next-day dedup and search read it.
-- Search ranks with ts_rank over the headline (weight A) and the source's own title (weight B).
CREATE TABLE story_sources (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id       bigint REFERENCES runs (id),
  headline     text NOT NULL,
  tier         text,
  source_id    text,
  source_title text,
  cluster_id   text,
  shown_at     timestamptz NOT NULL DEFAULT now(),
  search       tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(headline, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(source_title, '')), 'B')
  ) STORED
);
CREATE INDEX story_sources_shown_at ON story_sources (shown_at);
CREATE INDEX story_sources_source ON story_sources (source_id);
CREATE INDEX story_sources_run ON story_sources (run_id);
CREATE INDEX story_sources_search ON story_sources USING gin (search);

CREATE TABLE articles (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id        bigint REFERENCES runs (id),
  source_id     text NOT NULL,
  title         text NOT NULL,
  url           text NOT NULL,
  published_raw text,  -- the feed's own date text, unparsed
  summary       text,
  fetched_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX articles_run ON articles (run_id);
CREATE INDEX articles_source ON articles (source_id);

-- One row per feed fetched; run_id is NULL on rows recorded before runs were tracked.
CREATE TABLE source_fetches (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id           bigint REFERENCES runs (id),
  source_id        text NOT NULL,
  is_success       boolean NOT NULL,
  error            text,
  articles_fetched integer,
  articles_kept    integer,
  fetched_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX source_fetches_source ON source_fetches (source_id, fetched_at);
CREATE INDEX source_fetches_run ON source_fetches (run_id);

-- One row per fetched article dropped as a repeat of a recent headline.
CREATE TABLE dedup_matches (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id           bigint REFERENCES runs (id),
  title            text NOT NULL,
  source_id        text,
  matched_headline text NOT NULL,
  similarity       double precision NOT NULL,
  threshold        double precision NOT NULL,
  matched_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX dedup_matches_run ON dedup_matches (run_id);

-- Threads (§4.5). Every row belongs to the run that wrote it, so undoing a run deletes its rows and
-- touches no other run's. A thread's label, last run and status are derived (thread_state).
CREATE TABLE threads (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_run_id bigint NOT NULL REFERENCES runs (id),
  merged_into_id bigint REFERENCES threads (id),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX threads_merged_into ON threads (merged_into_id);

-- One run's entry on a thread; readers see it as an "update".
CREATE TABLE thread_updates (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id       bigint NOT NULL REFERENCES threads (id),
  run_id          bigint NOT NULL REFERENCES runs (id),
  label           text NOT NULL,  -- the story's cluster label that run
  is_continuation boolean NOT NULL,  -- the linker continued the thread, rather than starting it
  content         text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (thread_id, run_id)
);
CREATE INDEX thread_updates_run ON thread_updates (run_id);

CREATE TABLE thread_questions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id     bigint NOT NULL REFERENCES threads (id),
  question      text NOT NULL,
  raised_run_id bigint NOT NULL REFERENCES runs (id),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX thread_questions_thread ON thread_questions (thread_id);
CREATE INDEX thread_questions_raised ON thread_questions (raised_run_id);

CREATE TABLE thread_question_resolutions (
  question_id     bigint NOT NULL REFERENCES thread_questions (id),
  resolved_run_id bigint NOT NULL REFERENCES runs (id),
  answer          text NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (question_id, resolved_run_id)
);
CREATE INDEX thread_question_resolutions_run ON thread_question_resolutions (resolved_run_id);

-- What readers see of a thread: its published updates only. Dormant: more than 3 sent runs (the
-- pipeline's THREAD_DORMANT_AFTER default) between the latest published update and the newest run,
-- as the linker's decay counts them. A thread with no published update has no row.
CREATE VIEW thread_state AS
  WITH published AS (
    SELECT u.* FROM thread_updates u WHERE u.run_id IN (SELECT run_id FROM published_runs)
  ), latest AS (
    SELECT DISTINCT ON (thread_id) thread_id, run_id AS last_run_id, label, created_at AS updated_at
    FROM published ORDER BY thread_id, run_id DESC, id DESC
  )
  SELECT t.id, l.label,
         CASE
           WHEN t.merged_into_id IS NOT NULL THEN 'merged'
           WHEN (SELECT count(*) FROM sent_runs s
                 WHERE s.run_id > l.last_run_id AND s.run_id < (SELECT max(id) FROM runs)) > 3 THEN 'dormant'
           ELSE 'active'
         END AS status,
         t.created_run_id, l.last_run_id, t.created_at, l.updated_at, t.merged_into_id,
         (SELECT count(*) FROM published p WHERE p.thread_id = t.id) AS update_count
  FROM threads t JOIN latest l ON l.thread_id = t.id;

-- A question as readers see it: raised by a published run, resolved only by a published run.
CREATE VIEW thread_question_state AS
  SELECT q.id, q.thread_id, q.question, q.raised_run_id, r.resolved_run_id, r.answer,
         CASE WHEN r.question_id IS NULL THEN 'open' ELSE 'resolved' END AS status
  FROM thread_questions q
  LEFT JOIN LATERAL (
    SELECT question_id, resolved_run_id, answer FROM thread_question_resolutions x
    WHERE x.question_id = q.id AND x.resolved_run_id IN (SELECT run_id FROM published_runs)
    ORDER BY resolved_run_id LIMIT 1
  ) r ON true
  WHERE q.raised_run_id IN (SELECT run_id FROM published_runs);

-- migrate:down

DROP VIEW thread_question_state;
DROP VIEW thread_state;
DROP TABLE thread_question_resolutions;
DROP TABLE thread_questions;
DROP TABLE thread_updates;
DROP TABLE threads;
DROP TABLE dedup_matches;
DROP TABLE source_fetches;
DROP TABLE articles;
DROP TABLE story_sources;
DROP VIEW sent_runs;
DROP VIEW published_runs;
DROP TABLE sends;
DROP TABLE issues;
DROP TABLE model_calls;
DROP TABLE prompts;
DROP TABLE artifacts;
DROP TABLE run_attempts;
DROP TABLE runs;
DROP FUNCTION runs_transition();
