-- migrate:up

-- The product schema after the Python pipeline (docs/2026-09-23-data-model-design.md §4, and the
-- Postgres decision at its top). Written fresh: bin/import-legacy copies today's SQLite data into it.
-- Times are timestamptz in UTC. Ids are identities BY DEFAULT so the import can keep the legacy ids.

CREATE TABLE digest_runs (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_at           timestamptz NOT NULL DEFAULT now(),
  articles_kept    integer,
  articles_emailed integer DEFAULT 0,  -- the send's recipient count
  completed_at     timestamptz,        -- published: set only when the issue was sent
  git_sha          text,
  status           text NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'completed', 'failed')),
  -- 'unrecorded': imported Python runs marked completed with no evidence of a send.
  outcome          text CHECK (outcome IN ('sent', 'disabled', 'rejected', 'held-out', 'skipped', 'unrecorded')),
  error            text,
  CHECK ((status = 'completed') = (outcome IS NOT NULL)),
  CHECK (outcome IS DISTINCT FROM 'sent' OR completed_at IS NOT NULL),
  CHECK (completed_at IS NULL OR status = 'completed')
);
CREATE INDEX digest_runs_run_at ON digest_runs (run_at);

-- The lifecycle (§4.1): running -> completed(outcome) | failed; failed -> running (a resume);
-- completed -> running only while readers have nothing of it: not sent, and not in published_runs.
-- A published run is terminal: a forced re-run of its day is a new run. A write that leaves status
-- and outcome as they were is always allowed.
CREATE FUNCTION digest_runs_transition() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW.status = OLD.status AND NEW.outcome IS NOT DISTINCT FROM OLD.outcome)
     OR (OLD.status = 'running' AND NEW.status IN ('completed', 'failed'))
     OR (OLD.status = 'failed' AND NEW.status = 'running')
     OR (OLD.status = 'completed' AND OLD.outcome <> 'sent' AND NEW.status = 'running'
         AND NOT EXISTS (SELECT 1 FROM published_runs p WHERE p.run_id = OLD.id)) THEN
    RETURN NEW;
  END IF;
  RAISE EXCEPTION 'illegal digest_runs transition: % (%) -> % (%)', OLD.status, OLD.outcome, NEW.status, NEW.outcome
    USING ERRCODE = 'check_violation';
END
$$;
CREATE TRIGGER digest_runs_transition BEFORE UPDATE OF status, outcome ON digest_runs
  FOR EACH ROW EXECUTE FUNCTION digest_runs_transition();

CREATE TABLE run_attempts (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id          bigint NOT NULL REFERENCES digest_runs (id),
  pipeline        text NOT NULL CHECK (pipeline IN ('python', 'temporal')),
  workflow_id     text,
  workflow_run_id text UNIQUE,
  git_sha         text,
  forced          boolean NOT NULL DEFAULT false,
  started_at      timestamptz NOT NULL DEFAULT now(),
  ended_at        timestamptz,
  state           text NOT NULL DEFAULT 'running' CHECK (state IN ('running', 'finished', 'failed', 'closed_by_temporal')),
  error           text
);
CREATE INDEX run_attempts_run ON run_attempts (run_id);

-- A row is never overwritten: quarantine and force mark the old row and keep it, so the prior sample
-- survives, attributed to the attempt that produced it.
CREATE TABLE run_artifacts (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id        bigint NOT NULL REFERENCES digest_runs (id),
  attempt_id    bigint REFERENCES run_attempts (id),
  artifact_name text NOT NULL,
  content       text NOT NULL,
  sha256        text NOT NULL,
  state         text NOT NULL DEFAULT 'current' CHECK (state IN ('current', 'quarantined', 'replaced')),
  stage         text,
  kind          text,
  branch        text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX run_artifacts_current ON run_artifacts (run_id, artifact_name) WHERE state = 'current';
CREATE INDEX run_artifacts_run ON run_artifacts (run_id);

-- One row per system prompt and tool configuration, by content hash: local, A/B and replay runs have
-- no trustworthy image SHA, so git_sha cannot version a prompt.
CREATE TABLE prompts (
  sha256       text PRIMARY KEY,
  name         text NOT NULL,
  body         text NOT NULL,
  first_run_id bigint REFERENCES digest_runs (id)
);

-- One row per model call. Its inputs and output are artifacts (the corpus); full traces are not kept.
CREATE TABLE run_usage (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id             bigint NOT NULL REFERENCES digest_runs (id),
  attempt_id         bigint REFERENCES run_attempts (id),
  subagent           text NOT NULL,
  branch             text,
  model              text NOT NULL,
  input_tokens       integer NOT NULL DEFAULT 0,
  output_tokens      integer NOT NULL DEFAULT 0,
  cache_write_tokens integer NOT NULL DEFAULT 0,
  cache_read_tokens  integer NOT NULL DEFAULT 0,
  api_cost_usd       double precision NOT NULL DEFAULT 0,
  duration_ms        integer,
  thinking           text,
  effort             text,
  prompt_sha         text REFERENCES prompts (sha256),
  input_manifest     jsonb,
  output_artifact    text,
  result             text CHECK (result IN ('ok', 'invalid', 'error', 'timeout')),
  recorded_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX run_usage_run ON run_usage (run_id);

-- The web publication, append-only: a forced re-run adds a revision, never overwrites one. Inserted
-- after the pre-send hold, so an issue row means readers can see it. run_id is NULL only on five
-- issues imported from before runs were linked to issues.
CREATE TABLE issues (
  date         date NOT NULL,
  revision     integer NOT NULL CHECK (revision >= 1),
  run_id       bigint REFERENCES digest_runs (id),
  html         text NOT NULL,
  preheader    text NOT NULL DEFAULT '',
  published_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (date, revision)
);
CREATE INDEX issues_run ON issues (run_id);

-- The day's send, one per date: inserting the row is taking the claim. claim_token and claimed_at are
-- NULL only on sends imported from before claims were recorded.
CREATE TABLE broadcasts (
  date        date PRIMARY KEY,
  run_id      bigint NOT NULL REFERENCES digest_runs (id),
  claim_token text,
  claimed_at  timestamptz,
  resend_id   text UNIQUE,
  revision    integer NOT NULL,
  status      text NOT NULL CHECK (status IN ('claimed', 'draft', 'queued', 'sending', 'sent', 'failed')),
  recipients  integer,
  FOREIGN KEY (date, revision) REFERENCES issues (date, revision)
);
CREATE INDEX broadcasts_run ON broadcasts (run_id);

-- The one definition of "readers got this run": on the web, or handed to Resend (which cannot recall it).
CREATE VIEW published_runs AS
  SELECT run_id FROM issues WHERE run_id IS NOT NULL
  UNION
  SELECT run_id FROM broadcasts WHERE status IN ('queued', 'sending', 'sent');

-- One row per (story, source) shown; next-day dedup and search read it. Search ranks with ts_rank over
-- the headline (weight A) and the source's own title (weight B).
CREATE TABLE shown_narratives (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  headline       text NOT NULL,
  tier           text,
  shown_at       timestamptz NOT NULL DEFAULT now(),
  source_id      text,
  run_id         bigint REFERENCES digest_runs (id),
  original_title text,
  cluster_id     text,
  search         tsvector GENERATED ALWAYS AS (
    setweight(to_tsvector('english', coalesce(headline, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(original_title, '')), 'B')
  ) STORED
);
CREATE INDEX shown_narratives_shown_at ON shown_narratives (shown_at);
CREATE INDEX shown_narratives_source ON shown_narratives (source_id);
CREATE INDEX shown_narratives_run ON shown_narratives (run_id);
CREATE INDEX shown_narratives_search ON shown_narratives USING gin (search);

CREATE TABLE fetched_articles (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id     bigint REFERENCES digest_runs (id),
  source_id  text NOT NULL,
  title      text NOT NULL,
  url        text NOT NULL,
  published  text,  -- as the feed gave it
  summary    text,
  fetched_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX fetched_articles_run ON fetched_articles (run_id);
CREATE INDEX fetched_articles_source ON fetched_articles (source_id);

-- run_id is NULL on rows recorded before runs were tracked.
CREATE TABLE source_health (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_id        text NOT NULL,
  success          boolean NOT NULL,
  error_message    text,
  recorded_at      timestamptz NOT NULL DEFAULT now(),
  articles_fetched integer,
  articles_kept    integer,
  run_id           bigint REFERENCES digest_runs (id)
);
CREATE INDEX source_health_source ON source_health (source_id, recorded_at);
CREATE INDEX source_health_run ON source_health (run_id);

CREATE TABLE dedup_log (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  logged_at         timestamptz NOT NULL DEFAULT now(),
  article_title     text NOT NULL,
  article_source_id text,
  matched_headline  text NOT NULL,
  similarity        double precision NOT NULL,
  threshold         double precision NOT NULL,
  run_id            bigint REFERENCES digest_runs (id)
);
CREATE INDEX dedup_log_run ON dedup_log (run_id);

-- Threads (§4.5). Every row belongs to the run that wrote it, so undoing a run deletes its rows and
-- touches no other run's. A thread's label, last run and status are derived (thread_state).
CREATE TABLE threads (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_run_id bigint NOT NULL REFERENCES digest_runs (id),
  merged_into    bigint REFERENCES threads (id),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX threads_merged_into ON threads (merged_into);

CREATE TABLE thread_installments (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id     bigint NOT NULL REFERENCES threads (id),
  run_id        bigint NOT NULL REFERENCES digest_runs (id),
  cluster_story text NOT NULL,
  continued     boolean NOT NULL,  -- the linker continued the thread, rather than starting it
  content       text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (thread_id, run_id)
);
CREATE INDEX thread_installments_run ON thread_installments (run_id);

CREATE TABLE thread_questions (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id     bigint NOT NULL REFERENCES threads (id),
  question      text NOT NULL,
  raised_run_id bigint NOT NULL REFERENCES digest_runs (id),
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX thread_questions_thread ON thread_questions (thread_id);
CREATE INDEX thread_questions_raised ON thread_questions (raised_run_id);

CREATE TABLE thread_question_resolutions (
  question_id bigint NOT NULL REFERENCES thread_questions (id),
  run_id      bigint NOT NULL REFERENCES digest_runs (id),
  how         text NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (question_id, run_id)
);
CREATE INDEX thread_question_resolutions_run ON thread_question_resolutions (run_id);

-- What readers see of a thread: its published installments only. Dormant: more than 3 completed runs
-- (the pipeline's THREAD_DORMANT_AFTER default) between the latest published installment and the
-- newest run, as the linker's decay counts them. A thread with no published installment has no row.
CREATE VIEW thread_state AS
  WITH published AS (
    SELECT i.* FROM thread_installments i WHERE i.run_id IN (SELECT run_id FROM published_runs)
  ), latest AS (
    SELECT DISTINCT ON (thread_id) thread_id, run_id AS last_run_id, cluster_story AS label, created_at AS updated_at
    FROM published ORDER BY thread_id, run_id DESC, id DESC
  )
  SELECT t.id, l.label,
         CASE
           WHEN t.merged_into IS NOT NULL THEN 'merged'
           WHEN (SELECT count(*) FROM digest_runs r
                 WHERE r.id > l.last_run_id AND r.id < (SELECT max(id) FROM digest_runs) AND r.completed_at IS NOT NULL) > 3 THEN 'dormant'
           ELSE 'active'
         END AS status,
         t.created_run_id AS first_run_id, l.last_run_id, t.created_at, l.updated_at, t.merged_into,
         (SELECT count(*) FROM published p WHERE p.thread_id = t.id) AS installments
  FROM threads t JOIN latest l ON l.thread_id = t.id;

-- A question as readers see it: raised by a published run, resolved only by a published run.
CREATE VIEW thread_question_state AS
  SELECT q.id, q.thread_id, q.question, q.raised_run_id,
         r.run_id AS resolved_run_id, r.how AS resolved_how,
         CASE WHEN r.question_id IS NULL THEN 'open' ELSE 'resolved' END AS status
  FROM thread_questions q
  LEFT JOIN LATERAL (
    SELECT question_id, run_id, how FROM thread_question_resolutions x
    WHERE x.question_id = q.id AND x.run_id IN (SELECT run_id FROM published_runs)
    ORDER BY run_id LIMIT 1
  ) r ON true
  WHERE q.raised_run_id IN (SELECT run_id FROM published_runs);

-- migrate:down

DROP VIEW thread_question_state;
DROP VIEW thread_state;
DROP TABLE thread_question_resolutions;
DROP TABLE thread_questions;
DROP TABLE thread_installments;
DROP TABLE threads;
DROP TABLE dedup_log;
DROP TABLE source_health;
DROP TABLE fetched_articles;
DROP TABLE shown_narratives;
DROP VIEW published_runs;
DROP TABLE broadcasts;
DROP TABLE issues;
DROP TABLE run_usage;
DROP TABLE prompts;
DROP TABLE run_artifacts;
DROP TABLE run_attempts;
DROP TABLE digest_runs;
DROP FUNCTION digest_runs_transition();
