/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Articles {
  fetched_at: Generated<string>;
  id: Generated<number>;
  published_raw: string | null;
  run_id: number | null;
  source_id: string;
  summary: string | null;
  title: string;
  url: string;
}

export interface Artifacts {
  attempt_id: number | null;
  branch: string | null;
  content: string;
  created_at: Generated<string>;
  id: Generated<number>;
  kind: string | null;
  name: string;
  run_id: number;
  sha256: string;
  stage: string | null;
  status: Generated<string>;
}

export interface DedupMatches {
  id: Generated<number>;
  matched_at: Generated<string>;
  matched_headline: string;
  run_id: number | null;
  similarity: number;
  source_id: string | null;
  threshold: number;
  title: string;
}

export interface Issues {
  html: string;
  issue_date: string;
  markdown: string | null;
  preheader: Generated<string>;
  published_at: Generated<string>;
  revision: number;
  run_id: number | null;
}

export interface ModelCalls {
  api_cost_usd: Generated<number>;
  attempt_id: number | null;
  branch: string | null;
  cache_creation_input_tokens: Generated<number>;
  cache_read_input_tokens: Generated<number>;
  duration_ms: number | null;
  effort: string | null;
  id: Generated<number>;
  input_manifest: Json | null;
  input_tokens: Generated<number>;
  outcome: string | null;
  output_artifact: string | null;
  output_tokens: Generated<number>;
  prompt_sha256: string | null;
  recorded_at: Generated<string>;
  request_model: string;
  run_id: number;
  stage: string;
  thinking: string | null;
}

export interface Prompts {
  body: string;
  first_run_id: number | null;
  name: string;
  sha256: string;
}

export interface PublishedRuns {
  run_id: number | null;
}

export interface RunAttempts {
  ended_at: string | null;
  error: string | null;
  git_sha: string | null;
  id: Generated<number>;
  is_forced: Generated<boolean>;
  pipeline: string;
  run_id: number;
  started_at: Generated<string>;
  status: Generated<string>;
  workflow_id: string | null;
  workflow_run_id: string | null;
}

export interface Runs {
  articles_kept: number | null;
  error: string | null;
  git_sha: string | null;
  id: Generated<number>;
  outcome: string | null;
  started_at: Generated<string>;
  status: Generated<string>;
}

export interface Sends {
  claim_token: string | null;
  claimed_at: string | null;
  issue_date: string;
  recipients: number | null;
  resend_id: string | null;
  revision: number;
  run_id: number;
  status: string;
}

export interface SentRuns {
  run_id: number | null;
}

export interface SourceFetches {
  articles_fetched: number | null;
  articles_kept: number | null;
  error: string | null;
  fetched_at: Generated<string>;
  id: Generated<number>;
  is_success: boolean;
  run_id: number | null;
  source_id: string;
}

export interface StorySources {
  cluster_id: string | null;
  headline: string;
  id: Generated<number>;
  run_id: number | null;
  search: Generated<string | null>;
  search_simple: Generated<string | null>;
  shown_at: Generated<string>;
  source_id: string | null;
  source_title: string | null;
  tier: string | null;
}

export interface ThreadQuestionResolutions {
  answer: string;
  created_at: Generated<string>;
  question_id: number;
  resolved_run_id: number;
}

export interface ThreadQuestions {
  created_at: Generated<string>;
  id: Generated<number>;
  question: string;
  raised_run_id: number;
  thread_id: number;
}

export interface ThreadQuestionState {
  answer: string | null;
  id: number | null;
  question: string | null;
  raised_run_id: number | null;
  resolved_run_id: number | null;
  status: string | null;
  thread_id: number | null;
}

export interface Threads {
  created_at: Generated<string>;
  created_run_id: number;
  id: Generated<number>;
  merged_into_id: number | null;
}

export interface ThreadState {
  created_at: string | null;
  created_run_id: number | null;
  id: number | null;
  label: string | null;
  last_run_id: number | null;
  merged_into_id: number | null;
  status: string | null;
  update_count: number | null;
  updated_at: string | null;
}

export interface ThreadUpdates {
  content: string | null;
  created_at: Generated<string>;
  id: Generated<number>;
  is_continuation: boolean;
  label: string;
  run_id: number;
  thread_id: number;
}

export interface DB {
  articles: Articles;
  artifacts: Artifacts;
  dedup_matches: DedupMatches;
  issues: Issues;
  model_calls: ModelCalls;
  prompts: Prompts;
  published_runs: PublishedRuns;
  run_attempts: RunAttempts;
  runs: Runs;
  sends: Sends;
  sent_runs: SentRuns;
  source_fetches: SourceFetches;
  story_sources: StorySources;
  thread_question_resolutions: ThreadQuestionResolutions;
  thread_question_state: ThreadQuestionState;
  thread_questions: ThreadQuestions;
  thread_state: ThreadState;
  thread_updates: ThreadUpdates;
  threads: Threads;
}
