"""WRITE must see the headlines readers were recently shown.

Root cause of the null-delta continuation defect (measured 2026-07-25): a story
re-ships days later under a headline that restates the previous one, stamped
"Ongoing - day N". The delta was never missing -- for the two census cases that
were thread continuations, `thread_installments.whats_new` held 7 facts
(Burnham) and 5 (Spain wildfire) at the moment the stale headline was written.

The reason is ordering. `run.py` processes threads inside
`_archive_run_and_threads`, which runs AFTER assembly, so thread identity does
not exist while WRITE runs; `write.md` is handed no prior headline; and
`render.py` then replaces the SUMMARY with the delta and leaves the headline
untouched. SELECT already receives yesterday's editorial headlines (449fc60)
and correctly decides to re-cover an advancing story -- WRITE is the stage with
no memory at all.

The fix is transport, not detection: hand WRITE the headlines already shown in
the last week. Deliberately NOT a novelty detector -- the literature (TREC
Novelty F=0.185, TDT "First Story Detection is Hard", TREC Temporal
Summarization's unresolved precision/recall anti-correlation) puts the ceiling
around 75-80% on far richer input than RSS summaries, and every production
aggregator surveyed ranks on novelty rather than dropping on it. Nothing here
filters: a false match costs a few tokens of context, never a dropped story.

Window is 7 days because the observed re-ship gaps were +1d through +7d; a
yesterday-only window would miss half the census.
"""

import json
import logging
import sqlite3
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

import db

MIGRATIONS_DIR = Path(__file__).parent.parent.parent / "migrations"


@pytest.fixture
def fresh_db(tmp_path):
    db._state = db._State()
    db_path = tmp_path / "test.db"
    db.init(db_path, MIGRATIONS_DIR)
    return db_path


def _completed_run(db_path, *, days_ago: int, headlines: list[tuple[str, str]], completed: bool = True):
    """Insert a run `days_ago` days back with (tier, headline) pairs already shown.

    Timestamps are generated by SQLite itself so they are byte-identical in shape
    to production's `run_at` column default -- a Python-side ISO string with a
    timezone offset would test a format the pipeline never actually stores.
    """
    with sqlite3.connect(db_path) as conn:
        cur = conn.execute(
            "INSERT INTO digest_runs (run_at, completed_at) "
            "VALUES (datetime('now', :ago), CASE WHEN :completed THEN datetime('now', :ago) END)",
            {"ago": f"-{days_ago} days", "completed": completed},
        )
        run_id = cur.lastrowid
        for tier, headline in headlines:
            conn.execute(
                "INSERT INTO shown_narratives (headline, tier, source_id, run_id) VALUES (?, ?, ?, ?)",
                (headline, tier, "bbc", run_id),
            )
    return run_id


def _warnings(caplog) -> list[str]:
    """Warning messages captured so far -- listed rather than counted so a failing
    assertion prints what was (or was not) logged."""
    return [r.getMessage() for r in caplog.records if r.levelname == "WARNING"]


class TestRecentDigestHeadlines:
    def test_returns_headlines_inside_the_window(self, fresh_db):
        _completed_run(fresh_db, days_ago=1, headlines=[("must_know", "Burnham named Labour leader")])
        _completed_run(fresh_db, days_ago=3, headlines=[("should_know", "Kosovo holds third election")])

        got = {h["headline"] for h in db.get_recent_digest_headlines(days=7)}
        assert got == {"Burnham named Labour leader", "Kosovo holds third election"}

    def test_excludes_runs_outside_the_window(self, fresh_db):
        _completed_run(fresh_db, days_ago=1, headlines=[("must_know", "Recent story")])
        _completed_run(fresh_db, days_ago=30, headlines=[("must_know", "Ancient story")])

        got = {h["headline"] for h in db.get_recent_digest_headlines(days=7)}
        assert got == {"Recent story"}

    def test_excludes_runs_that_never_completed(self, fresh_db):
        """An aborted run's headlines never reached a reader, so they are not
        'what we already told them' -- including them would suppress a genuinely
        unseen story."""
        _completed_run(fresh_db, days_ago=1, headlines=[("must_know", "Delivered")])
        _completed_run(fresh_db, days_ago=1, headlines=[("must_know", "Aborted")], completed=False)

        got = {h["headline"] for h in db.get_recent_digest_headlines(days=7)}
        assert got == {"Delivered"}

    def test_dedupes_repeated_headlines(self, fresh_db):
        """shown_narratives stores one row PER SOURCE, not per story (mean 2.10,
        max 48). Without dedup a four-source story floods the context four times."""
        _completed_run(
            fresh_db,
            days_ago=1,
            headlines=[("must_know", "Same story"), ("must_know", "Same story"), ("must_know", "Same story")],
        )
        assert [h["headline"] for h in db.get_recent_digest_headlines(days=7)] == ["Same story"]

    def test_tier_and_date_come_from_the_newest_showing(self, fresh_db):
        """The query leans on SQLite's bare-column rule to carry `tier` alongside
        MAX(run_at), which is only defined while there is exactly ONE min/max
        aggregate in the statement. Adding a second, different one (the obvious
        next feature: "when was this first shown?") silently starts returning an
        arbitrary row's tier. test_dedupes_repeated_headlines cannot catch that --
        it uses one tier for every row -- so this is the guard."""
        _completed_run(fresh_db, days_ago=3, headlines=[("must_know", "Same headline, different day")])
        _completed_run(fresh_db, days_ago=1, headlines=[("should_know", "Same headline, different day")])

        rows = db.get_recent_digest_headlines(days=7)
        assert len(rows) == 1
        assert rows[0]["tier"] == "should_know", "tier must come from the most recent showing"

    def test_newest_first(self, fresh_db):
        _completed_run(fresh_db, days_ago=5, headlines=[("must_know", "Older")])
        _completed_run(fresh_db, days_ago=1, headlines=[("must_know", "Newer")])

        assert [h["headline"] for h in db.get_recent_digest_headlines(days=7)] == ["Newer", "Older"]

    def test_empty_when_no_history(self, fresh_db):
        assert db.get_recent_digest_headlines(days=7) == []


class TestEmptyIsNotSilent:
    """Zero headlines is normal on a fresh install and a BUG on a populated DB.

    A tier rename, a `completed_at` regression, or a run_id backfill gap all make
    this query match nothing WITHOUT raising sqlite3.Error -- it stays
    syntactically valid, just selects no rows. The observable outcome is then
    byte-identical to "there is genuinely no history": no file, no warning, and
    WRITE silently reverts to the pre-fix behaviour this whole change exists to
    prevent. That is the shape that made wire_agency a no-op through 841 green
    tests, so the empty path has to be able to tell the two apart.
    """

    def test_warns_when_completed_runs_exist_but_no_headlines(self, fresh_db, caplog):
        # A completed run whose rows are all a tier this query does not select:
        # exactly what a tier rename would look like.
        _completed_run(fresh_db, days_ago=1, headlines=[("signal", "Not a digest tier")])

        with caplog.at_level(logging.WARNING):
            assert db.get_recent_digest_headlines(days=7) == []
        warnings = _warnings(caplog)
        assert warnings, "populated DB returning nothing must be loud"
        assert "completed" in warnings[0].lower()

    def test_quiet_on_a_genuinely_fresh_install(self, fresh_db, caplog):
        """No completed runs at all -> nothing is wrong, so nothing is logged at
        WARNING. Otherwise every first run of a new deployment cries wolf."""
        with caplog.at_level(logging.WARNING):
            assert db.get_recent_digest_headlines(days=7) == []
        assert _warnings(caplog) == []

    def test_quiet_on_the_happy_path(self, fresh_db, caplog):
        _completed_run(fresh_db, days_ago=1, headlines=[("must_know", "A real headline")])
        with caplog.at_level(logging.WARNING):
            assert len(db.get_recent_digest_headlines(days=7)) == 1
        assert _warnings(caplog) == []


class TestPrepareWritesTheFile:
    """prepare.py must land the file WRITE reads, alongside the SELECT one."""

    def _run_prepare(self, tmp_path, recent):
        fetched_dir = tmp_path / "fetched"
        fetched_dir.mkdir()
        (fetched_dir / "bbc.json").write_text(
            json.dumps([{"title": "T", "url": "https://bbc.com/1", "published": "2026-07-25", "summary": "S"}])
        )
        sources = [
            {"id": "bbc", "name": "BBC", "url": "u", "bias": "center", "factuality": "high", "perspective": "UK"}
        ]
        input_dir = tmp_path / "claude_input"
        with (
            patch("prepare.CLAUDE_INPUT_DIR", input_dir),
            patch("prepare.FETCHED_DIR", fetched_dir),
            patch("prepare.OUTPUT_DIR", tmp_path / "out"),
            patch("prepare.DATA_DIR", tmp_path / "data"),
            patch("prepare.get_previous_headlines", return_value=[]),
            patch("prepare.get_yesterday_digest_headlines", return_value=[]),
            patch("prepare.get_recent_digest_headlines", return_value=recent),
            patch("prepare.log_dedup_action"),
        ):
            from prepare import prepare_claude_input

            prepare_claude_input(sources)
        return input_dir / "recent_digest_headlines.txt"

    def test_writes_recent_headlines_file(self, tmp_path):
        path = self._run_prepare(
            tmp_path,
            [
                {"headline": "Burnham named Labour leader", "tier": "must_know", "date": "2026-07-17"},
                {"headline": "Kosovo holds third election", "tier": "should_know", "date": "2026-07-15"},
            ],
        )
        assert path.exists()
        body = path.read_text()
        # Pin the EXACT line, not its parts. write.md documents the format to the
        # model as `date | tier: headline`, so prepare.py and the prompt are a
        # contract; substring assertions would stay green against JSON, CSV, or a
        # reordered `tier | date: headline`.
        assert "2026-07-17 | must_know: Burnham named Labour leader\n" in body
        assert "2026-07-15 | should_know: Kosovo holds third election\n" in body

    def test_preserves_newest_first_order(self, tmp_path):
        """The DB returns newest-first and the prompt tells the model the file IS
        newest-first; nothing else pins that prepare.py doesn't reorder it."""
        path = self._run_prepare(
            tmp_path,
            [
                {"headline": "Newer", "tier": "must_know", "date": "2026-07-17"},
                {"headline": "Older", "tier": "must_know", "date": "2026-07-15"},
            ],
        )
        lines = path.read_text().splitlines()
        assert [line.split(": ", 1)[1] for line in lines] == ["Newer", "Older"]

    def test_no_file_when_no_history(self, tmp_path):
        """Matches the neighbouring yesterday_headlines.txt behaviour: absent
        rather than empty, so the prompt's "skip if not found" branch is real."""
        assert not self._run_prepare(tmp_path, []).exists()
