#!/bin/sh
# usage: scripts/schema-types.sh [kysely-codegen options, e.g. --verify or --print]
# The product schema's row types (src/store/schema.gen.ts), generated by kysely-codegen from a fresh
# database migrated with every migration in db/migrations: the types can only say what the
# migrations make. Runs in the ci-ts container, beside ci-pg (DIGEST_TEST_DATABASE_URL); `make
# schema-types` regenerates the file, and src/store/schema-types.test.ts fails CI while it is stale.
# The type mapping (.kysely-codegenrc.json) follows the pool's parsers in src/store/db.ts: bigints and
# numerics as numbers, dates and times as text.
set -eu
cd "$(dirname "$0")/.."
admin=${DIGEST_TEST_DATABASE_URL:?DIGEST_TEST_DATABASE_URL names a Postgres server to make the database on}
db=schema_types_$$_$(date +%s)
url=$(printf '%s' "$admin" | sed -E "s#/[^/?]+(\?|\$)#/$db\1#")
psql -q "$admin" -c "CREATE DATABASE $db"
trap 'psql -q "$admin" -c "DROP DATABASE IF EXISTS $db" >/dev/null' EXIT
npx dbmate --url "$url" --migrations-dir db/migrations --no-dump-schema up >/dev/null
npx kysely-codegen --config-file .kysely-codegenrc.json --url "$url" --log-level error "$@"
